# Generated by Django 4.0.1 on 2022-01-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('tittle', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
    ]
