# Generated by Django 4.0.1 on 2022-01-20 05:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0003_sportnews_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 20, 5, 27, 19, 333776, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sportnews',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 20, 5, 27, 19, 369075, tzinfo=utc)),
        ),
    ]
